[metadata]
    name = gradvi
    author = Saikat Banerjee
    author_email = banskt.saikat@gmail.com
    copyright = Saikat Banerjee
    contributors = Saikat Banerjee
    license = MIT
    description = Gradient descent methods for variational inference with mean field approximation
    keywords = variational inference, gradient descent, mean field, empirical Bayes

#   setup_requires are required before running setuptools
#   install_requires are required before installation
#   comma, separated, list, of, packages
    setup_requires = numpy
    install_requires = scipy
    min_python = 3.6
    max_python = 9.99
    min_numpy = 1.16.5
    max_numpy = 9.9.99

#   list of all URLs
    main_url = https://github.com/banskt/gradvi
    download_url = https://github.com/banskt/gradvi
    git_url = https://github.com/banskt/gradvi
    docs_url = https://github.com/banskt/gradvi
    source_code_url = https://github.com/banskt/gradvi
    bug_tracker_url = https://github.com/banskt/gradvi


#   for a list of classifiers, see:
#   https://pypi.org/classifiers/
    classifiers = 
        Development Status :: 4 - Beta
        Intended Audience :: Education
        Intended Audience :: Science/Research
        Programming Language :: Python :: 3
        Programming Language :: Python :: 3 :: Only
        Programming Language :: Python :: 3.6
        Programming Language :: Python :: 3.7
        Programming Language :: Python :: 3.8
        Operating System :: POSIX
        Topic :: Scientific/Engineering :: Artificial Intelligence
        License :: OSI Approved :: MIT License
    git_branch = master
    host = github
    zip_safe = False
    release_branch = False

#   Package information
    srcdir = src

# [info]
#     STATUSES = 
#         1 - Planning,
#         2 - Pre-Alpha,
#         3 - Alpha,
#         4 - Beta,
#         5 - Production/Stable,
#         6 - Mature,
#         7 - Inactive
